// sidebars.js
module.exports = {
  docs: [
    { type: 'doc', id: 'intro', label: 'Introduction' },
    { type: 'doc', id: 'before_you_start', label: 'Before You Start' },
    { type: 'doc', id: 'use_cases', label: 'Use Cases' },
    { type: 'doc', id: 'architecture', label: 'Architecture' },
    { type: 'doc', id: 'installation_upgrade', label: 'Installation & Upgrade' },
    { type: 'doc', id: 'quickstart', label: 'Quickstart' },
    { type: 'doc', id: 'image_catalog', label: 'Image Catalog' },
    { type: 'doc', id: 'bootstrap', label: 'Bootstrap' },
    { type: 'doc', id: 'database_import', label: 'Database Import' },
    { type: 'doc', id: 'security', label: 'Security' },
    { type: 'doc', id: 'instance_manager', label: 'Instance Manager' },
    { type: 'doc', id: 'scheduling', label: 'Scheduling' },
    { type: 'doc', id: 'resource_management', label: 'Resource Management' },
    { type: 'doc', id: 'failure_modes', label: 'Failure Modes' },
    { type: 'doc', id: 'rolling_update', label: 'Rolling Update' },
    { type: 'doc', id: 'replication', label: 'Replication' },
    { type: 'doc', id: 'logical_replication', label: 'Logical Replication' },
    { type: 'doc', id: 'backup', label: 'Backup' },
    { type: 'doc', id: 'wal_archiving', label: 'WAL Archiving' },
    { type: 'doc', id: 'recovery', label: 'Recovery' },
    { type: 'doc', id: 'service_management', label: 'Service Management' },
    { type: 'doc', id: 'postgresql_conf', label: 'PostgreSQL Config' },
    { type: 'doc', id: 'declarative_role_management', label: 'Declarative Role Management' },
    { type: 'doc', id: 'declarative_database_management', label: 'Declarative Database Management' },
    { type: 'doc', id: 'tablespaces', label: 'Tablespaces' },
    { type: 'doc', id: 'operator_conf', label: 'Operator Config' },
    { type: 'doc', id: 'cluster_conf', label: 'Cluster Config' },
    { type: 'doc', id: 'storage', label: 'Storage' },
    { type: 'doc', id: 'labels_annotations', label: 'Labels & Annotations' },
    { type: 'doc', id: 'monitoring', label: 'Monitoring' },
    { type: 'doc', id: 'logging', label: 'Logging' },
    { type: 'doc', id: 'certificates', label: 'Certificates' },
    { type: 'doc', id: 'ssl_connections', label: 'SSL Connections' },
    { type: 'doc', id: 'applications', label: 'Applications' },
    { type: 'doc', id: 'connection_pooling', label: 'Connection Pooling' },
    { type: 'doc', id: 'replica_cluster', label: 'Replica Cluster' },
    { type: 'doc', id: 'kubernetes_upgrade', label: 'Kubernetes Upgrade' },
    { type: 'doc', id: 'postgres_upgrades', label: 'Postgres Upgrades' },
    { type: 'doc', id: 'kubectl-plugin', label: 'kubectl Plugin' },
    { type: 'doc', id: 'failover', label: 'Failover' },
    { type: 'doc', id: 'troubleshooting', label: 'Troubleshooting' },
    { type: 'doc', id: 'fencing', label: 'Fencing' },
    { type: 'doc', id: 'declarative_hibernation', label: 'Declarative Hibernation' },
    { type: 'doc', id: 'postgis', label: 'PostGIS' },
    { type: 'doc', id: 'e2e', label: 'E2E' },
    { type: 'doc', id: 'container_images', label: 'Container Images' },
    { type: 'doc', id: 'operator_capability_levels', label: 'Operator Capability Levels' },
    { type: 'doc', id: 'controller', label: 'Controller' },
    { type: 'doc', id: 'samples', label: 'Samples' },
    { type: 'doc', id: 'networking', label: 'Networking' },
    { type: 'doc', id: 'benchmarking', label: 'Benchmarking' },
    { type: 'doc', id: 'faq', label: 'FAQ' },
    { type: 'doc', id: 'cloudnative-pg.v1', label: 'API Reference' },
    { type: 'doc', id: 'supported_releases', label: 'Supported Releases' },
    { type: 'doc', id: 'preview_version', label: 'Preview Version' },
    { type: 'doc', id: 'release_notes', label: 'Release Notes' },
    {
      type: 'category',
      label: 'CNCF Projects Integrations',
      collapsed: true,
      items: [
        { type: 'doc', id: 'cncf-projects/external-secrets', label: 'External Secrets' },
        { type: 'doc', id: 'cncf-projects/cilium', label: 'Cilium' }
      ]
    },
    {
      type: 'category',
      label: 'Appendixes',
      collapsed: true,
      items: [
        { type: 'doc', id: 'appendixes/backup_volumesnapshot', label: 'Backup VolumeSnapshot' },
        { type: 'doc', id: 'appendixes/backup_barmanobjectstore', label: 'Backup BarmanObjectStore' },
        { type: 'doc', id: 'appendixes/object_stores', label: 'Object Stores' }
      ]
    }
  ]
};
