// sidebars.js

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // '.' means scan all docs starting from root `docs/`
    },
  ],
};

module.exports = sidebars;